//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.eFP.WebJob.Email.Application.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATS.eFP.WebJob.Email.Application.Localization.LocalizedText", typeof(LocalizedText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Description:.
        /// </summary>
        public static string AssetDescription {
            get {
                return ResourceManager.GetString("AssetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Id:.
        /// </summary>
        public static string AssetId {
            get {
                return ResourceManager.GetString("AssetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset #:.
        /// </summary>
        public static string AssetNum {
            get {
                return ResourceManager.GetString("AssetNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Technician:.
        /// </summary>
        public static string AssignedTech {
            get {
                return ResourceManager.GetString("AssignedTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BldgLoc:.
        /// </summary>
        public static string BldgLoc {
            get {
                return ResourceManager.GetString("BldgLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bldg Location:.
        /// </summary>
        public static string BldgLocation {
            get {
                return ResourceManager.GetString("BldgLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central Standard Time.
        /// </summary>
        public static string CentralTime {
            get {
                return ResourceManager.GetString("CentralTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of Issue:.
        /// </summary>
        public static string DescriptionIssue {
            get {
                return ResourceManager.GetString("DescriptionIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eastern Standard Time.
        /// </summary>
        public static string EasternTime {
            get {
                return ResourceManager.GetString("EasternTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquipCrit:.
        /// </summary>
        public static string EquipCrit {
            get {
                return ResourceManager.GetString("EquipCrit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EquipDescr:.
        /// </summary>
        public static string EquipDescr {
            get {
                return ResourceManager.GetString("EquipDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Criticality:.
        /// </summary>
        public static string EquipmentCriticality {
            get {
                return ResourceManager.GetString("EquipmentCriticality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment ID:.
        /// </summary>
        public static string EquipmentId {
            get {
                return ResourceManager.GetString("EquipmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-location:.
        /// </summary>
        public static string EquipmentSublocation {
            get {
                return ResourceManager.GetString("EquipmentSublocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escalated At:.
        /// </summary>
        public static string EscalatedAt {
            get {
                return ResourceManager.GetString("EscalatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escalation Notification - Work Order is Completed.
        /// </summary>
        public static string EscalationCompleted {
            get {
                return ResourceManager.GetString("EscalationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escalation Notification.
        /// </summary>
        public static string EscalationOpen {
            get {
                return ResourceManager.GetString("EscalationOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Monitor Description:.
        /// </summary>
        public static string EventMonitorDescription {
            get {
                return ResourceManager.GetString("EventMonitorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Monitor Information.
        /// </summary>
        public static string EventMonitorInformation {
            get {
                return ResourceManager.GetString("EventMonitorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Monitor Name:.
        /// </summary>
        public static string EventMonitorName {
            get {
                return ResourceManager.GetString("EventMonitorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malfunction Start:.
        /// </summary>
        public static string MalfunctionStart {
            get {
                return ResourceManager.GetString("MalfunctionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malfunction Stop:.
        /// </summary>
        public static string MalfunctionStop {
            get {
                return ResourceManager.GetString("MalfunctionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mountain Standard Time.
        /// </summary>
        public static string MountainTime {
            get {
                return ResourceManager.GetString("MountainTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No equip on WO, only Sublocation.
        /// </summary>
        public static string NoEquip {
            get {
                return ResourceManager.GetString("NoEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repair remarks.
        /// </summary>
        public static string NoRepairRemarks {
            get {
                return ResourceManager.GetString("NoRepairRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Status:.
        /// </summary>
        public static string OperationalStatus {
            get {
                return ResourceManager.GetString("OperationalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpStatus:.
        /// </summary>
        public static string OpStatus {
            get {
                return ResourceManager.GetString("OpStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pacific Standard Time.
        /// </summary>
        public static string PacificTime {
            get {
                return ResourceManager.GetString("PacificTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site:.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order {0} Completed.
        /// </summary>
        public static string SubjectCompleted {
            get {
                return ResourceManager.GetString("SubjectCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order {0} Created.
        /// </summary>
        public static string SubjectCreated {
            get {
                return ResourceManager.GetString("SubjectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subloc:.
        /// </summary>
        public static string Subloc {
            get {
                return ResourceManager.GetString("Subloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sublocation:.
        /// </summary>
        public static string Sublocation {
            get {
                return ResourceManager.GetString("Sublocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Template:.
        /// </summary>
        public static string TaskTemplate {
            get {
                return ResourceManager.GetString("TaskTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician Remarks:.
        /// </summary>
        public static string TechnicianRemarks {
            get {
                return ResourceManager.GetString("TechnicianRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WO#:.
        /// </summary>
        public static string WO {
            get {
                return ResourceManager.GetString("WO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Priority:.
        /// </summary>
        public static string WorkOrdedrPriority {
            get {
                return ResourceManager.GetString("WorkOrdedrPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your work order {0}, has been completed..
        /// </summary>
        public static string WorkOrderCompleted {
            get {
                return ResourceManager.GetString("WorkOrderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your work order {0}, has been created..
        /// </summary>
        public static string WorkOrderCreated {
            get {
                return ResourceManager.GetString("WorkOrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Date/Time:.
        /// </summary>
        public static string WorkOrderDateTime {
            get {
                return ResourceManager.GetString("WorkOrderDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Description:.
        /// </summary>
        public static string WorkOrderDescription {
            get {
                return ResourceManager.GetString("WorkOrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have an account, you may view this Work Order in:.
        /// </summary>
        public static string WorkorderFooter {
            get {
                return ResourceManager.GetString("WorkorderFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Number:.
        /// </summary>
        public static string WorkOrderNumber {
            get {
                return ResourceManager.GetString("WorkOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Status:.
        /// </summary>
        public static string WorkOrderStatus {
            get {
                return ResourceManager.GetString("WorkOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Type:.
        /// </summary>
        public static string WorkOrderType {
            get {
                return ResourceManager.GetString("WorkOrderType", resourceCulture);
            }
        }
    }
}
